#!/usr/bin/env python3
"""Regenerate languages/PROGRESS.md from the current filesystem state.

The table lists every language with tick marks for each required file and
vocabulary/example coverage against its tier target.

Usage:
    python languages/scripts/build_progress.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LANG_LIST = ROOT / "languages" / "language_list.json"
LANG_DIR = ROOT / "languages"
PROGRESS = ROOT / "languages" / "PROGRESS.md"

MIN_MD_CHARS = 400
TIER_VOCAB = {"high": 10000, "mid": 5000, "low": 1000}
MD_FILES = ["overview.md", "grammar.md", "characteristics.md", "differences.md"]


def md_done(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    return "<!-- TODO" not in text and len(text) >= MIN_MD_CHARS


def vocab_count(path: Path) -> int:
    if not path.exists():
        return 0
    try:
        return len(json.loads(path.read_text(encoding="utf-8")).get("words", []))
    except json.JSONDecodeError:
        return 0


def count_examples(d: Path) -> int:
    if not d.exists():
        return 0
    return sum(1 for p in d.glob("*.txt") if p.stat().st_size >= 100)


def tick(b: bool) -> str:
    return "x" if b else " "


def main() -> int:
    data = json.loads(LANG_LIST.read_text(encoding="utf-8"))
    rows = []
    for entry in data["languages"]:
        code, folder, tier, name = entry["code"], entry["folder"], entry["tier"], entry["name"]
        ldir = LANG_DIR / folder
        mds = {m: md_done(ldir / m) for m in MD_FILES}
        vocab = vocab_count(ldir / "vocabulary.json")
        target = TIER_VOCAB[tier]
        exs = count_examples(ldir / "examples")
        all_md = all(mds.values())
        vocab_pct = min(100, int(100 * vocab / target)) if target else 0
        rows.append({
            "code": code, "folder": folder, "name": name, "tier": tier,
            "overview": mds["overview.md"], "grammar": mds["grammar.md"],
            "chars": mds["characteristics.md"], "diffs": mds["differences.md"],
            "vocab": vocab, "target": target, "vocab_pct": vocab_pct,
            "examples": exs, "all_md": all_md,
        })

    complete = sum(1 for r in rows if r["all_md"] and r["vocab"] >= r["target"] and r["examples"] >= 10)
    lines = []
    lines.append("# CommonLID Language Knowledge Base — Progress\n")
    lines.append(f"_Auto-generated by `scripts/build_progress.py`. "
                 f"{complete}/{len(rows)} languages complete._\n")
    lines.append("")
    lines.append("| code | folder | tier | ov | gr | ch | df | vocab | examples |")
    lines.append("|------|--------|------|----|----|----|----|-------|----------|")
    for r in rows:
        lines.append(
            f"| {r['code']} | `{r['folder']}` | {r['tier']} | "
            f"[{tick(r['overview'])}] | [{tick(r['grammar'])}] | [{tick(r['chars'])}] | [{tick(r['diffs'])}] | "
            f"{r['vocab']}/{r['target']} ({r['vocab_pct']}%) | {r['examples']} |"
        )
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("- **ov / gr / ch / df** — `overview.md`, `grammar.md`, `characteristics.md`, `differences.md` (each must exceed the placeholder threshold).")
    lines.append("- **vocab** — words in `vocabulary.json`. Target depends on resource tier: high = 10k, mid = 5k, low = 1k.")
    lines.append("- **examples** — number of files in `examples/` that are at least 100 characters long.")
    lines.append("")

    PROGRESS.write_text("\n".join(lines), encoding="utf-8")
    print(f"[info] wrote {PROGRESS}; {complete}/{len(rows)} complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
