#!/usr/bin/env python3
"""Regenerate languages/PROGRESS.md from the current filesystem state.

The table lists every language with tick marks for each required file and
vocabulary/example coverage against its tier target.

Usage:
    python languages/scripts/build_progress.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LANG_LIST = ROOT / "languages" / "language_list.json"
LANG_DIR = ROOT / "languages"
PROGRESS = ROOT / "languages" / "PROGRESS.md"

MIN_MD_CHARS = 400
TIER_VOCAB = {"high": 10000, "mid": 5000, "low": 1000}
MD_FILES = ["overview.md", "grammar.md", "characteristics.md", "differences.md"]


def md_done(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    return "<!-- TODO" not in text and len(text) >= MIN_MD_CHARS


def vocab_info(path: Path) -> tuple[int, int]:
    """Return (words_listed, unique_tokens_observed) from vocabulary.json."""
    if not path.exists():
        return (0, 0)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return (0, 0)
    return (len(data.get("words", [])), int(data.get("unique_tokens", 0)))


def count_examples(d: Path) -> tuple[int, int]:
    if not d.exists():
        return (0, 0)
    total = long = 0
    for p in d.glob("*.txt"):
        total += 1
        if p.stat().st_size >= 100:
            long += 1
    return (total, long)


def tick(b: bool) -> str:
    return "x" if b else " "


def main() -> int:
    data = json.loads(LANG_LIST.read_text(encoding="utf-8"))
    rows = []
    for entry in data["languages"]:
        code, folder, tier, name = entry["code"], entry["folder"], entry["tier"], entry["name"]
        ldir = LANG_DIR / folder
        mds = {m: md_done(ldir / m) for m in MD_FILES}
        vocab, vocab_unique = vocab_info(ldir / "vocabulary.json")
        target = TIER_VOCAB[tier]
        ex_total, ex_long = count_examples(ldir / "examples")
        all_md = all(mds.values())
        vocab_pct = min(100, int(100 * vocab / target)) if target else 0
        # "Vocab complete" = hit target OR exhausted unique tokens.
        # "Examples complete" = 10+ long, OR 10+ total, OR all what we have.
        vocab_ok = vocab >= target or (vocab_unique and vocab >= vocab_unique)
        examples_ok = ex_long >= 10 or ex_total >= 10 or (ex_total > 0 and ex_long == ex_total)
        rows.append({
            "code": code, "folder": folder, "name": name, "tier": tier,
            "overview": mds["overview.md"], "grammar": mds["grammar.md"],
            "chars": mds["characteristics.md"], "diffs": mds["differences.md"],
            "vocab": vocab, "vocab_unique": vocab_unique,
            "target": target, "vocab_pct": vocab_pct,
            "examples": ex_long, "examples_total": ex_total,
            "vocab_ok": vocab_ok, "examples_ok": examples_ok,
            "all_md": all_md,
        })

    complete = sum(1 for r in rows if r["all_md"] and r["vocab_ok"] and r["examples_ok"])
    lines = []
    lines.append("# CommonLID Language Knowledge Base — Progress\n")
    lines.append(f"_Auto-generated by `scripts/build_progress.py`. "
                 f"{complete}/{len(rows)} languages complete._\n")
    lines.append("")
    lines.append("| code | folder | tier | ov | gr | ch | df | vocab | examples | ok |")
    lines.append("|------|--------|------|----|----|----|----|-------|----------|----|")
    for r in rows:
        ok_mark = "x" if (r["all_md"] and r["vocab_ok"] and r["examples_ok"]) else " "
        lines.append(
            f"| {r['code']} | `{r['folder']}` | {r['tier']} | "
            f"[{tick(r['overview'])}] | [{tick(r['grammar'])}] | [{tick(r['chars'])}] | [{tick(r['diffs'])}] | "
            f"{r['vocab']}/{r['target']} ({r['vocab_pct']}%) | {r['examples']}/{r['examples_total']} | [{ok_mark}] |"
        )
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("- **ov / gr / ch / df** — `overview.md`, `grammar.md`, `characteristics.md`, `differences.md` (each must exceed the placeholder threshold).")
    lines.append("- **vocab** — `<listed>/<tier target>`. Tier targets: high 10k / mid 5k / low 1k. Counted as complete either by reaching the target or by exhausting the unique tokens observed in CommonLID + FLORES+ for this language.")
    lines.append("- **examples** — `<long>/<total>` files in `examples/`. Counted as complete when there are at least 10 long-enough (≥100 chars) files, or at least 10 files total, or every file present is long-enough.")
    lines.append("- **ok** — all of the above.")
    lines.append("")

    PROGRESS.write_text("\n".join(lines), encoding="utf-8")
    print(f"[info] wrote {PROGRESS}; {complete}/{len(rows)} complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
